### ISSUE TITLE
Refactor: one column with full name should be centered 

### ISSUE THREAD

**Issue by Julikoo** [Fidge123/tippspiel#12]
<img width="1332" alt="Bildschirmfoto 2020-10-09 um 14 39 45" src="https://user-images.githubusercontent.com/11096501/95584135-81afd880-0a3d-11eb-848d-4c107ee6da7e.png">

Like shown in the image the one column view with full name is not centered but it should be.

**Comment by Fidge123** [comment]
When considering the current implementation of the leaderboard (which you dont see due to missing auth), it is centered...

<img width="1379" alt="Screen Shot 2020-10-16 at 16 21 37" src="https://user-images.githubusercontent.com/4191406/96270243-ac64d880-0fcb-11eb-873d-39c9c65792d1.png">

This hopefully isnt an issue once #4 is completed.
